name: Generate JSON file

on:
  push:
    branches:
      - main

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get file names and URLs
      run: |
        files=$(curl -Ls https://api.github.com/repos/${{ github.repository }}/contents)
        file_count=$(echo $files | jq '. | length')
        file_names=$(echo $files | jq -r '.[].name')
        file_urls=$(echo $files | jq -r '.[].download_url')
        echo "File names: $file_names"
        echo "File URLs: $file_urls"
        
    - name: Generate JSON file
      run: |
        echo '[' > file_data.json
        for file_name in $file_names; do
          file_url=$(echo "$file_urls" | awk -v name="$file_name" '$0 ~ name {print $0; exit}')
          echo "  {\"name\": \"$file_name\", \"url\": \"$file_url\"}," >> file_data.json
        done
        sed -i '$ s/.$//' file_data.json
        echo ']' >> file_data.json

    - name: Upload JSON file
      uses: actions/upload-artifact@v2.2.1
      with:
        name: file_data.json
        path: file_data.json
