name: Generate JSON file

on:
  push:
    branches:
      - main

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get list of files
      run: |
        files=$(ls)
        echo "::set-output name=files::$files"

    - name: Add files to JSON file
      run: |
        files=$(echo "${{ steps.get-files.outputs.files }}" | tr ' ' '\n')
        for file in $files; do
          echo "Adding $file to JSON file"
          echo "name":"$file" >> files.txt
        done


    - name: Upload JSON file
      uses: actions/upload-artifact@v2
      with:
        name: files
        path: files.txt
