name: Generate JSON file

on:
  push:
    branches:
      - main

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get file names and URLs
      run: |
        files=$(curl -Ls https://api.github.com/repos/${{ github.repository }}/contents)
        file_names=$(echo $files | jq -r '.[].name')
        file_urls=$(echo $files | jq -r '.[].download_url')

        file_data="$(echo "$file_names" | awk '{print NR "," $0}')"
        file_data="$file_data $(echo "$file_urls" | awk '{print NR "," $0}')"

    - name: Generate JSON file
      run: |
        echo '{' > file_data.json
        echo "$file_data" | awk -F, '{print "\""$2"\": \""$3"\""}' | tr '\n' ',' >> file_data.json
        echo '}' >> file_data.json

    - name: Upload JSON file
      uses: actions/upload-artifact@v3
      with:
        name: file_data.json
        path: file_data.json
