name: Generate JSON file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get MP3 files
      run: |
        echo "Collecting MP3 files..."
        mp3_files=$(find . -type f -name "*.mp3")
        echo "Found the following MP3 files:"
        echo "$mp3_files"

    - name: Generate JSON file
      run: |
        echo "Generating JSON file..."
        echo '{"files": [' > file_list.json
        while read -r line; do
          file_name=$(basename "$line")
          echo "    {\"file_name\": \"$file_name\", \"file_link\": \"https://github.com/$GITHUB_REPOSITORY/raw/main/$line\"}," >> file_list.json
        done <<< "$mp3_files"
        echo "  ]}" >> file_list.json

    - name: Commit and push JSON file
      uses: actions/github-script@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          echo "Committing and pushing JSON file..."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add file_list.json
          git commit -m "Add file_list.json"
          git push origin main
