# This is a basic workflow to help you get started with Actions

name: fileCheck

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  getList:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run a one-line script
        id: fileListGet
        uses: the-coding-turtle/ga-file-list@v0.2
        with:
          file_extension: "mp3"
  saveList:
    runs-on: ubuntu-latest
    needs: getList
    steps:
      - run: echo ${{needs.getList.outputs.files}} > listShit.txt
      - name: upload shit  
        uses: actions/upload-artifact@v3
        with:
          name: listShit
          path: listShit.txt

      
    
