name: Generate JSON file

on:
  push:
    branches:
      - main

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get list of files
      run: |
        files=$(ls)
        echo "::set-output name=files::$files"

    - name: Add files to JSON file
      run: |
        echo '{"songs": [' > songs.json
        files=$(echo "${{ steps.get-files.outputs.files }}" | tr ' ' '\n')
        for file in $files; do
          echo "Adding $file to JSON file"
          echo "  {\"name\": \"$file\", \"url\": \"URL\"}," >> songs.json
        done
        echo ']}' >> songs.json

    - name: Upload JSON file
      uses: actions/upload-artifact@v2
      with:
        name: songs.json
        path: songs.json
