name: Generate JSON file

on:
  push:
    branches:
      - main

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get list of files
      run: |
        files=$(ls)
        echo "::set-output name=files::$files"

    - name: Add files to JSON file
      run: |
        files=$(echo "${{ steps.get-files.outputs.files }}" | tr ' ' '\n')
        for file in $files; do
          echo "Adding $file to JSON file"
          # Add code to add each file to a JSON file here
        done
